name: ci

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check Docker version
        run: |
          docker --version

      -  name: Build Docker Image
         run: |
          docker build -t my-image:v1 .
         working-directory: ./


      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v2
        with:
            access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
            region: us-east-1
            image: my-image:v1
